name: DDPM For Background Correction

model_settings:
  ch: 64
  ch_mult: [1, 2, 2, 4, 4]
  num_res_blocks: 2
  dropout: 0.
  attn_ds: [16]
  use_torch_attn: False
  size: 256
  input_ch: 3

ddpm_settings:
  T: 1000
  beta_scdl: linear
  beta_1: 1.e-4
  beta_T: 0.02