name: Self-attention model for sinogram alignment

data_settings:
  max_shift: 50
  
training_settings:
  trn_data_dir: Sino_Train
  model_save_dir: checkpoints
  ckpt_path: alignment_ep500.pt
  device: cuda:0
  n_epochs: 500
  save_n_epochs: 100
  visualize_n_epochs: 1
  batch_size: 32
  base_lr: 1.e-4
  weight_decay: 1.e-4
  grad_clip: 1
  use_cosine_annealing: true      
  warmup_epochs: 5              
  eta_min: 1.e-6                  
  T_max: ~   

model_settings:
  embed_dim: 512
  num_att_blocks: 4
  num_align_blocks: 1
  num_heads: 4
  mlp_ratio: 4
  dropout: 0.1