name: Self-attention model for sinogram alignment

training_settings:
  model_save_dir: Sinogram_Alignment/checkpoints
  ckpt_path: ~
  device: cuda:0
  n_epochs: 1200
  save_n_epochs: 200
  batch_size: 32
  base_lr: 2.e-4
  weight_decay: 1.e-4

model_settings:
  ch: 256
  num_att_blocks: 4
  dropout: 0.2